### ISSUE TITLE
Bug when I move around the menu.

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#110]
1) Try to delete a session
2) Continue without saving

`Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Engenharia\Programaçao\Python\Projects\whatsapp-play\wplay\__main__.py", line 114, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 612, in run_until_complete
    return future.result()
  File "D:\Engenharia\Programaçao\Python\Projects\whatsapp-play\wplay\__main__.py", line 108, in main
    await match_args(args)
  File "D:\Engenharia\Programaçao\Python\Projects\whatsapp-play\wplay\__main__.py", line 88, in match_args
    await messageblast.blast(args.name)
  File "D:\Engenharia\Programaçao\Python\Projects\whatsapp-play\wplay\messageblast.py", line 7, in blast
    pages, browser = await pypConfig.configure_browser_and_load_whatsapp(pypConfig.websites['whatsapp'])
  File "D:\Engenharia\Programaçao\Python\Projects\whatsapp-play\wplay\pyppeteerUtils\pyppeteerConfig.py", line 45, in configure_browser_and_load_whatsapp    username, save_session = __session_mananger()
  File "D:\Engenharia\Programaçao\Python\Projects\whatsapp-play\wplay\pyppeteerUtils\pyppeteerConfig.py", line 143, in __session_mananger
    return username, save_session
UnboundLocalError: local variable 'username' referenced before assignment`

**Comment by xandao6** [comment]
Solved by: #117
