### ISSUE TITLE
whatsapp-play not executing with -wt command

### ISSUE THREAD

**Issue by GeniusLearner** [rpotter12/whatsapp-play#132]
## Expected Behavior

Able to successfully execute the command `wplay -wt "XXXXXXXXX"`

`XXXXXXXXX` is the phone number with international code attached.

## Actual Behavior

The command fails after choosing a session and gives the following core dump:

```
Process Killed!
Traceback (most recent call last):
  File "/home/geniuslearner/personal/proj_whatsapp_play/venv/bin/wplay", line 5, in <module>
    from wplay.__main__ import main
  File "/home/geniuslearner/personal/proj_whatsapp_play/venv/lib/python3.7/site-packages/wplay/__main__.py", line 115, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/geniuslearner/personal/proj_whatsapp_play/venv/lib/python3.7/site-packages/wplay/__main__.py", line 109, in main
    await match_args(args)
  File "/home/geniuslearner/personal/proj_whatsapp_play/venv/lib/python3.7/site-packages/wplay/__main__.py", line 80, in match_args
    await onlinetracker.tracker(args.target)
  File "/home/geniuslearner/personal/proj_whatsapp_play/venv/lib/python3.7/site-packages/wplay/onlinetracker.py", line 13, in tracker
    page, _ = await browser_config.configure_browser_and_load_whatsapp()
  File "/home/geniuslearner/personal/proj_whatsapp_play/venv/lib/python3.7/site-packages/wplay/utils/browser_config.py", line 43, in configure_browser_and_load_whatsapp
    browser = await __config_browser(username, save_session)
  File "/home/geniuslearner/personal/proj_whatsapp_play/venv/lib/python3.7/site-packages/wplay/utils/browser_config.py", line 80, in __config_browser
    userDataDir=user_data_folder_path/username
  File "/home/geniuslearner/personal/proj_whatsapp_play/venv/lib/python3.7/site-packages/pyppeteer/launcher.py", line 311, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/geniuslearner/personal/proj_whatsapp_play/venv/lib/python3.7/site-packages/pyppeteer/launcher.py", line 189, in launch
    self.browserWSEndpoint = self._get_ws_endpoint()
  File "/home/geniuslearner/personal/proj_whatsapp_play/venv/lib/python3.7/site-packages/pyppeteer/launcher.py", line 233, in _get_ws_endpoint
    self.proc.stdout.read().decode()
pyppeteer.errors.BrowserError: Browser closed unexpectedly:
[32129:32129:0225/010949.065428:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x55804bf1179c base::debug::StackTrace::StackTrace()
#1 0x55804be911c0 logging::LogMessage::~LogMessage()
#2 0x55804d2b1830 service_manager::ZygoteHostImpl::Init()
#3 0x55804bb8365e content::ContentMainRunnerImpl::Initialize()
#4 0x55804bbb7b08 service_manager::Main()
#5 0x55804bb81be1 content::ContentMain()
#6 0x55804a0341b3 ChromeMain
#7 0x7f98fb16709b __libc_start_main
#8 0x55804a03402a _start

Received signal 6
#0 0x55804bf1179c base::debug::StackTrace::StackTrace()
#1 0x55804bf11301 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f98fd5d1730 <unknown>
#3 0x7f98fb17a7bb gsignal
#4 0x7f98fb165535 abort
#5 0x55804bf10155 base::debug::BreakDebugger()
#6 0x55804be91629 logging::LogMessage::~LogMessage()
#7 0x55804d2b1830 service_manager::ZygoteHostImpl::Init()
#8 0x55804bb8365e content::ContentMainRunnerImpl::Initialize()
#9 0x55804bbb7b08 service_manager::Main()
#10 0x55804bb81be1 content::ContentMain()
#11 0x55804a0341b3 ChromeMain
#12 0x7f98fb16709b __libc_start_main
#13 0x55804a03402a _start
  r8: 0000000000000000  r9: 00007fff0ccb8550 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007fff0ccb8c58 r13: 000000000000016d r14: 00007fff0ccb8c60 r15: 00007fff0ccb8c68
  di: 0000000000000002  si: 00007fff0ccb8550  bp: 00007fff0ccb87a0  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f98fb17a7bb  sp: 00007fff0ccb8550
  ip: 00007f98fb17a7bb efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

```

Upon researching this error, it showed that it required chromium, so I installed it on my laptop, but I'm still facing the issue and I haven't found anything else that would help in fixing this issue.

## Specifications

  - Version: 10
  - Platform: Debian

**Comment by rpotter12** [comment]
@GeniusLearner Is it working with name for you??

**Comment by GeniusLearner** [comment]
@rpotter12 No, it's not working with name.

**Comment by rpotter12** [comment]
clone the repository then use following commands:
- `cd whatsapp-play`
- `pip3 install -e .`

Maybe this works

**Comment by xandao6** [comment]
Currently we are not able to search for a number, only for contacts in you list.

**Comment by xandao6** [comment]
> clone the repository then use following commands:
> 
> * `cd whatsapp-play`
> * `pip3 install -e .`
> 
> Maybe this works

If you wanna use venv:
clone, cd
python3 -m venv .venv
source .venv/bin/activate
you can install or not, without installing: python -m wplay -wb any_name
If you wanna install: python -m pip install -e .

**Comment by Neelaksh-Singh** [comment]
![image](https://user-images.githubusercontent.com/56018436/76160631-bf6c1c00-6151-11ea-914e-6a8e464ae525.png)


this is the current status of my installation

**Comment by rpotter12** [comment]
@Neelaksh-Singh install transitions library by `pip install transitions`

**Comment by Neelaksh-Singh** [comment]
![image](https://user-images.githubusercontent.com/56018436/76163067-13362f80-6169-11ea-8182-3fb5ccf233a2.png)
 

Done sir.
Thank U
