### ISSUE TITLE
Error when downloading chromium

### ISSUE THREAD

**Issue by tyren542** [rpotter12/whatsapp-play#261]
Hi, when i try to download chromium to start the tracking i get this error, what could i do to fix it?

`? ***Session Manager***:  Create a new session
? Write your first name or username to save:  ciao
[W:pyppeteer.chromium_downloader] start chromium download.
Download may take a few minutes.
Process Killed!
Traceback (most recent call last):
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "C:\Users\Manuel\miniconda3\lib\site-packages\OpenSSL\SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\Manuel\miniconda3\lib\site-packages\OpenSSL\SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\Manuel\miniconda3\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\connection.py", line 360, in connect
    ssl_context=context,
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\util\ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Manuel\miniconda3\Scripts\wplay-script.py", line 11, in <module>
    load_entry_point('wplay', 'console_scripts', 'wplay')()
  File "C:\Users\Manuel\miniconda3\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\Manuel\miniconda3\lib\site-packages\pkg_resources\__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "C:\Users\Manuel\miniconda3\lib\site-packages\pkg_resources\__init__.py", line 2445, in load
    return self.resolve()
  File "C:\Users\Manuel\miniconda3\lib\site-packages\pkg_resources\__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\manuel\whatsapp-play\wplay\__main__.py", line 161, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\Manuel\miniconda3\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "c:\users\manuel\whatsapp-play\wplay\__main__.py", line 154, in main
    await get_and_match_args(parser)
  File "c:\users\manuel\whatsapp-play\wplay\__main__.py", line 113, in get_and_match_args
    await onlinetracker.tracker(args.target)
  File "c:\users\manuel\whatsapp-play\wplay\onlinetracker.py", line 20, in tracker
    page, _ = await browser_config.configure_browser_and_load_whatsapp()
  File "c:\users\manuel\whatsapp-play\wplay\utils\browser_config.py", line 39, in configure_browser_and_load_whatsapp
    browser = await __config_browser(username, save_session)
  File "c:\users\manuel\whatsapp-play\wplay\utils\browser_config.py", line 83, in __config_browser
    userDataDir = user_data_folder_path / username
  File "C:\Users\Manuel\miniconda3\lib\site-packages\pyppeteer\launcher.py", line 311, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\Manuel\miniconda3\lib\site-packages\pyppeteer\launcher.py", line 125, in __init__
    download_chromium()
  File "C:\Users\Manuel\miniconda3\lib\site-packages\pyppeteer\chromium_downloader.py", line 136, in download_chromium
    extract_zip(download_zip(get_url()), DOWNLOADS_FOLDER / REVISION)
  File "C:\Users\Manuel\miniconda3\lib\site-packages\pyppeteer\chromium_downloader.py", line 78, in download_zip
    data = http.request('GET', url, preload_content=False)
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\Manuel\miniconda3\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /chromium-browser-snapshots/Win_x64/575458/chrome-win32.zip (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
PS C:\Users\Manuel\whatsapp-play>`

**Comment by rpotter12** [comment]
@tyren542 It might be related to #126 issue.

**Comment by tyren542** [comment]
Thank you, with your help i solved this problem with chromium, now i have another one, when the contact i choose to track goes online the file status_contactname does not get updated, how do i make the script save the data? I have to end the script with a specific command instead of just closing it?

**Comment by rpotter12** [comment]
> I have to end the script with a specific command instead of just closing it?

use `ctrl + c` to end the script. 
> when the contact i choose to track goes online the file status_contactname does not get updated, how do i make the script save the data?

The script tracks the data and save that data in wplay folder. I'm not understanding what you exactly want to say??
