### ISSUE TITLE
ImportError: cannot import name 'Deque'

### ISSUE THREAD

**Issue by ahmed-gelemli** [rpotter12/whatsapp-play#278]
`C:\Users\ahmed\OneDrive\Desktop\whatsapp-play>python -m wplay -h`
```
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ahmed\OneDrive\Desktop\whatsapp-play\wplay\__main__.py", line 10, in <module>
    from wplay import online_tracker
  File "C:\Users\ahmed\OneDrive\Desktop\whatsapp-play\wplay\online_tracker.py", line 5, in <module>
    from wplay.utils import browser_config
  File "C:\Users\ahmed\OneDrive\Desktop\whatsapp-play\wplay\utils\browser_config.py", line 27, in <module>
    import websockets.client
  File "C:\Program Files\Python36\lib\site-packages\websockets\__init__.py", line 3, in <module>
    from .auth import *
  File "C:\Program Files\Python36\lib\site-packages\websockets\auth.py", line 15, in <module>
    from .server import HTTPResponse, WebSocketServerProtocol
  File "C:\Program Files\Python36\lib\site-packages\websockets\server.py", line 49, in <module>
    from .protocol import WebSocketCommonProtocol
  File "C:\Program Files\Python36\lib\site-packages\websockets\protocol.py", line 18, in <module>
    from typing import (
ImportError: cannot import name 'Deque'
```
My **Python** version is:
`Python 3.6.0`

**Comment by xandao6** [comment]
https://stackoverflow.com/questions/60011092/importerror-cannot-import-name-deque

**Comment by rpotter12** [comment]
@ahmed-gelemli Install python3.6.1+ version. This will solve your problem.

**Comment by ahmed-gelemli** [comment]
> @ahmed-gelemli Install python3.6.1+ version. This will solve your problem.

I installed Python 3.7, but a new issue appeared. I reported this issue here > #280 .

`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ahmed\\wplay\\logs\\wplay.log'`
