### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/wplay/logs/wplay.log'

### ISSUE THREAD

**Issue by ahmed-gelemli** [rpotter12/whatsapp-play#280]
`username@MY-PC:~/whatsapp-play$ wplay
`
```
> Traceback (most recent call last):
>   File "/home/username/.local/bin/wplay", line 6, in <module>
>     from wplay.__main__ import main
>   File "/home/username/.local/lib/python3.7/site-packages/wplay/__main__.py", line 10, in <module>
>     from wplay import online_tracker
>   File "/home/username/.local/lib/python3.7/site-packages/wplay/online_tracker.py", line 5, in <module>
>     from wplay.utils import browser_config
>   File "/home/username/.local/lib/python3.7/site-packages/wplay/utils/browser_config.py", line 39, in <module>
>     __logger = Logger(Path(__file__).name)
>   File "/home/username/.local/lib/python3.7/site-packages/wplay/utils/Logger.py", line 16, in __init__
>     file_handler = logging.FileHandler(logs_path/'wplay.log')
>   File "/usr/lib/python3.7/logging/__init__.py", line 1087, in __init__
>     StreamHandler.__init__(self, self._open())
>   File "/usr/lib/python3.7/logging/__init__.py", line 1116, in _open
>     return open(self.baseFilename, self.mode, encoding=self.encoding)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/username/wplay/logs/wplay.log'
```

If Someone Knows the Solution to this Error Please Help.
Thanks!

**Comment by rpotter12** [comment]
@ahmed-gelemli You need to install python3.6.1+ version

**Comment by xandao6** [comment]
@rpotter12  he is using python 3.7

**Comment by ahmed-gelemli** [comment]
> @rpotter12 he is using python 3.7

Yes, I am using Python 3.7 but same issue

**Comment by xandao6** [comment]
@ahmed-gelemli you can create this file manually: '/home/username/wplay/logs/wplay.log'. 
I will verify why the file wasn't created automatically.

**Comment by xandao6** [comment]
@ahmed-gelemli  bug fixed, wait for @rpotter12 to merge the PR.

**Comment by rpotter12** [comment]
> @rpotter12 he is using python 3.7

Ahhh....I have commented on this issue by mistakenly.
