### ISSUE TITLE
Opening issue

### ISSUE THREAD

**Issue by wirkoo** [rpotter12/whatsapp-play#376]
When i type python3 -m wplay -wt (or every other available option instead of -wt), It shows me the following error. Please guide

Process Killed!
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wirkoo/Desktop/whatsapp-play/wplay/__main__.py", line 216, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/wirkoo/Desktop/whatsapp-play/wplay/__main__.py", line 209, in main
    await get_and_match_args(parser)
  File "/home/wirkoo/Desktop/whatsapp-play/wplay/__main__.py", line 186, in get_and_match_args
    await about_changer.about_changer()
  File "/home/wirkoo/Desktop/whatsapp-play/wplay/about_changer.py", line 20, in about_changer
    await change_about()
  File "/home/wirkoo/Desktop/whatsapp-play/wplay/about_changer.py", line 27, in change_about
    page, _ = await browser_config.configure_browser_and_load_whatsapp()
  File "/home/wirkoo/Desktop/whatsapp-play/wplay/utils/browser_config.py", line 59, in configure_browser_and_load_whatsapp
    browser = await __config_browser(username, save_session)
  File "/home/wirkoo/Desktop/whatsapp-play/wplay/utils/browser_config.py", line 127, in __config_browser
    return await launch(headless=False, autoClose=False, userDataDir=user_data_folder_path / username)
  File "/home/wirkoo/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/wirkoo/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/home/wirkoo/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 225, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

**Comment by rpotter12** [comment]
It's better to install this software by `pip3 install wplay` and use like this `wplay -wt`.

I need to know few things:
1. output of `$ pwd`
2. OS?
3. Reinstall pyppeteer library.

It might be possible that whatsapp has changed their HTML format, so it can give this type of error. I will check this and fix this soon.

**Comment by rpotter12** [comment]
@wirkoo Whatsapp changes their HTML format every month. So we have old selectors in the script. I will fix this soon and if you like to solve this you are most welcome :)

**Comment by wirkoo** [comment]
Bro i don't have such experience, i was just trying to use the program. Please tell me if there is any way to overcome the problem and run the program. I am using kali linux. 
If there is any way that i may not use the latest version of whatsapp and the one working with your program....... until you fix this.

**Comment by rpotter12** [comment]
Actually this software works on particular selectors, so we can't use it until we fix the selectors.

**Comment by rpotter12** [comment]
@wirkoo tracking scripts are now working. You can check.
