### ISSUE TITLE
not bale to launch usinh wplay -h getting teh following errors

### ISSUE THREAD

**Issue by internetpoint** [rpotter12/whatsapp-play#385]
Traceback (most recent call last):
  File "/usr/local/bin/wplay", line 6, in <module>
    from wplay.__main__ import main
  File "/usr/local/lib/python3.7/dist-packages/wplay/__main__.py", line 15, in <module>
    from wplay import broadcast_message
  File "/usr/local/lib/python3.7/dist-packages/wplay/broadcast_message.py", line 2, in <module>
    from tkinter import Tk
ModuleNotFoundError: No module named 'tkinter'

**Comment by rpotter12** [comment]
Try to install tkinter. This can help you.

**Comment by rpotter12** [comment]
Hi @bitaashna, try these commands:
```
$ sudo apt update
$ sudo apt upgrade
$ sudo apt-get install python-tk
```

**Comment by bitaashna** [comment]
![Screenshot from 2021-03-10 19-20-58](https://user-images.githubusercontent.com/57864526/110639523-d1a1ef80-81d5-11eb-8b00-6b8260fbbbfb.png)
again facing the same problem..unable to install tkinter

**Comment by rpotter12** [comment]
@bitaashna you are trying to install tkinter on python2. Use command `sudo apt-get install python3-tk` to install it in python3.

**Comment by bitaashna** [comment]
tried that also.. but still the problem persist
![Screenshot from 2021-03-11 08-47-11](https://user-images.githubusercontent.com/57864526/110730441-74925200-8246-11eb-9e80-439d443d09c1.png)

**Comment by bitaashna** [comment]
Though I was not able to run this on ubuntu ,I switched my OS to windows and now it's working fine.

**Comment by rpotter12** [comment]
@bitaashna, We need to solve your ubuntu issue also. This should not happen. I will look at tkinter library. I am not sure that we are using tkinter in this software or not.
