### ISSUE TITLE
Error when running in Windows 10 - online tracking

### ISSUE THREAD

**Issue by Tudorvr** [rpotter12/whatsapp-play#88]
When running in terminal "wplay -wt xxx", it returns me this error after opening Chrome and recognizing the whatsapp web session from mobile phone. Have any idea how could I solve it? I run it on Windows 10, python 3.7 or python 3.6...

 DevTools listening on ws://127.0.0.1:54026/devtools/browser/5e3587e5-85b6-41b2-aa5b-0c7e220cf6cb
Looking for: xxx
Traceback (most recent call last):
  File "C:\Users\.....AppData\Local\Programs\Python\Python37-32\Scripts\wplay-script.py", line 11, in <module>
    load_entry_point('wplay==3.0.0', 'console_scripts', 'wplay')()
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wplay\wplay.py", line 97, in main
    match_args(args)
  File "C:\Users\....\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wplay\wplay.py", line 69, in match_args
    onlinetracker.tracker(args.name)
  File "C:\Users\....\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wplay\onlinetracker.py", line 14, in tracker
    sel.find_and_navigate_to_target(driver_wait, chosen_website, name)
  File "C:\Users\....\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wplay\seleniumUtils.py", line 37, in find_and_navigate_to_target
    person_title.click()
  File "C:\Users\....\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\....\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=79.0.3945.88)

Many thanks!

**Comment by rpotter12** [comment]
@Tudorvr I have tested this software with the same configuration you have. I don't know why this occurs.
Please uninstall it by `pip uninstall wplay` and again install it.
and if you again get any error then share your screenshot of the whole error with the command you used. :)

**Comment by xandao6** [comment]
I think this error occurs because selenium clicks quickly on the person and sometimes the element is not fully charged.
This error will be fixed soon with Pyppeteer!

For now we can try this between line 47 and 48 from seleniumUtils.py
   ` time.sleep(5)`

**Comment by rpotter12** [comment]
This can be possible.

**Comment by rpotter12** [comment]
this is solved by #92
