### ISSUE TITLE
empty page in chrome with "data:," in address bar

### ISSUE THREAD

**Issue by d2e4c6d8** [rpotter12/whatsapp-play#91]
with latest whatsapp play v3.0.0 with latest chrome (79.0.3945.117) and Chromedriver (79.0.3945.36) 
wplay -wt username
chrome shows empty page with only "data:," in address bar
What could be the cause of this ?
Thanks!

**Comment by xandao6** [comment]
Any error messages on the terminal?

**Comment by d2e4c6d8** [comment]
Yes, but only after Chrome terminates by itself (that takes a while):
Traceback (most recent call last):
  File "....\python\v3\Scripts\wplay-script.py", line 11, in <module>
    load_entry_point('wplay==3.0.0', 'console_scripts', 'wplay')()
  File "....\python\v3\lib\site-packages\wplay\wplay.py", line 97, in main
    match_args(args)
  File "....\python\v3\lib\site-packages\wplay\wplay.py", line 69, in match_args
    onlinetracker.tracker(args.name)
  File "....\python\v3\lib\site-packages\wplay\onlinetracker.py", line 12, in tracker
    sel.websites['whatsapp'])
  File "....\python\v3\lib\site-packages\wplay\seleniumUtils.py", line 23, in initialize_chrome_driver
    driver = webdriver.Chrome(ChromeDriverManager().install())
  File "....\python\v3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "....\python\v3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "....\python\v3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "....\python\v3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "....\python\v3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable

**Comment by xandao6** [comment]
Could you test with chrome version 79.0.3945.88?

**Comment by d2e4c6d8** [comment]
I got it resolved. The problem was blocked inbound connections to chrome in firewall. It used to work that way with previous versions. Thanks!
